version: "3.7"
services:

    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu

    rabbitmq:
        image: rabbitmq:3-management-alpine

    mtk-client:
        build: MTK.Client/.

    rank-api:
        build:
            context: .
            dockerfile: MTK.RankAPI/Dockerfile
        depends_on: 
            - sql-server

    syllabus-api:
        build:
            context: .
            dockerfile: MTK.SyllabusAPI/Dockerfile
        depends_on: 
            - sql-server
