version: "3.7"
services:
    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    mtk-client:
        build: MTK.Client/.
    rank-api:
        build: MTK.RankAPI/.
        depends_on: 
            - sql-server
